apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx
        ports:
        - containerPort: 8080
        env:
        - name: NGINX_HTTP_PORT_NUMBER
          value: "8080"
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8081
        env:
        - name: HTTP_PORT
          value: "8081"
